# Generated by Django 5.2.8 on 2025-11-24 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название категории помощи')),
                ('is_other', models.BooleanField(default=False, verbose_name="Является 'Другое'")),
                ('status', models.IntegerField(default=0, verbose_name='Статус')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sadaqa.language')),
            ],
            options={
                'verbose_name': 'Категория помощи',
                'verbose_name_plural': 'Категории помощи',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('why_collecting', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='companies/')),
                ('status', models.IntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadaqa.language')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Семейное положение')),
                ('status', models.IntegerField(default=0, verbose_name='Статус')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadaqa.language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Семейное положение',
                'verbose_name_plural': 'Семейные положения',
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('age', models.IntegerField(blank=True, default=0, verbose_name='Возраст')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('other_category', models.CharField(blank=True, max_length=250, null=True, verbose_name='Другая категория')),
                ('child_in_fam', models.IntegerField(blank=True, default=0, verbose_name='Количество детей')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('iin', models.CharField(blank=True, max_length=12, verbose_name='ИИН')),
                ('why_need_help', models.TextField(verbose_name='Причина обращения за помощью')),
                ('file', models.FileField(blank=True, upload_to='uploads/', verbose_name='Изображение')),
                ('money', models.FloatField()),
                ('status', models.IntegerField(default=0, verbose_name='Статус')),
                ('help_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sadaqa.helpcategory', verbose_name='Категория помощи')),
                ('material_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadaqa.materialsstatus', verbose_name='Семейное положение')),
            ],
            options={
                'verbose_name': 'Заявка на помощь',
                'verbose_name_plural': 'Заявки на помощь',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notes/')),
                ('title', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('goal_money', models.FloatField()),
                ('collected_money', models.FloatField()),
                ('type', models.CharField(choices=[('normal', 'Обычный'), ('medium', 'Средний'), ('urgent', 'Срочный'), ('very_urgent', 'Очень срочный')], default='normal', max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadaqa.language')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadaqa.language')),
            ],
        ),
    ]
